site_name: I7 Handbook
site_url: https://github.com/omartek/I7handbook_byJimAikin
docs_dir: gitbook/
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - inform7
nav:
    - 'Chapter 1': '/chapter_1_getting_started/'
    - 'Chapter 1': '/chapter_2_rooms_&_scenery/'
