site_name: I7 Handbook
site_url: https://github.com/omartek/I7handbook_byJimAikin
docs_dir: gitbook/
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - inform7
nav:
    - 'Chapter 1': '/chapter_1_getting_started/getting_started.md'
    - 'Getting_started': '/chapter_1_getting_started/downloading_&_installing.md'
    - 'The Inform 7 Program': '/chapter_1_getting_started/the_inform_7_program.md'
    - 'Using the Built-In Documentation': '/chapter_1_getting_started/using_the_built-in_documentation.md'
    - 'What Happens in a Game': '/chapter_1_getting_started/what_happens_in_a_game.md'
    - 'Downloading & Playing Games': '/chapter_1_getting_started/downloading_&_playing_games.md'
    - 'Writing Your First Game': '/chapter_1_getting_started/writing_your_first_game.md'
    - 'All About Bugs': '/chapter_1_getting_started/all_about_bugs.md'
    - 'Testing Your Game': '/chapter_1_getting_started/testing_your_game.md'
    - 'Using the Debugging Commands': '/chapter_1_getting_started/using_the_debugging_commands.md'
    - 'Puzzles': '/chapter_1_getting_started/puzzles.md'
    - 'Extensions for Inform': '/chapter_1_getting_started/extensions_for_inform.md'
    - 'Where to Learn More': '/chapter_1_getting_started/where_to_learn_more.md'
