site_name: I7 Handbook
site_url: https://github.com/omartek/I7handbook_byJimAikin
docs_dir: gitbook/
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - inform7
nav:
    - Getting started: '/chapter_1_getting_started/getting_started.md'
    - Chapter 1 - Getting started:
                - Getting started: '/chapter_1_getting_started/getting_started.md'
                - Downloading & installing: '/chapter_1_getting_started/downloading_&_installing.md'
