site_name: I7 Handbook
site_url: https://github.com/omartek/I7handbook_byJimAikin
docs_dir: gitbook/
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - inform7
nav:
    - ' Inform7 - I7Handbook':
        - 'Info & Licence': 'README.md'
        - 'Foreword': './foreword/foreword.md'
        - 'Acknowledgments': './foreword/acknowledgments.md'
        - 'About the Author': './foreword/about_the_author.md'
    - 'Chapter 1 - Getting started':
        - 'Getting started': './chapter_1_getting_started/getting_started.md'
        - 'Downloading & installing': './chapter_1_getting_started/downloading_&_installing.md'
        - 'The Inform 7 Program': './chapter_1_getting_started/the_inform_7_program.md'
        - 'Using the Built-In Documentation': './chapter_1_getting_started/using_the_built-in_documentation.md'
        - 'What Happens in a Game': './chapter_1_getting_started/what_happens_in_a_game.md'
        - 'Downloading & Playing Games': './chapter_1_getting_started/downloading_&_playing_games.md'
        - 'Writing Your First Game': './chapter_1_getting_started/writing_your_first_game.md'
        - 'All About Bugs': './chapter_1_getting_started/all_about_bugs.md'
        - 'Testing Your Game': './chapter_1_getting_started/testing_your_game.md'
        - 'Using the Debugging Commands': './chapter_1_getting_started/using_the_debugging_commands.md'
        - 'Puzzles': './chapter_1_getting_started/puzzles.md'
        - 'Extensions for Inform': './chapter_1_getting_started/extensions_for_inform.md'
        - 'Where to Learn More': './chapter_1_getting_started/where_to_learn_more.md'
    - 'Chapter 2: Rooms & Scenery':
        - 'Rooms & Scenery': './chapter_2_rooms_&_scenery/rooms_&_scenery.md'
        - 'Creating Your First Room': './chapter_2_rooms_&_scenery/creating_your_first_room.md'
        - 'Scenery': './chapter_2_rooms_&_scenery/scenery.md'
        - 'Distant Scenery': './chapter_2_rooms_&_scenery/distant_scenery.md'
        - 'Adding More Rooms to the Map': './chapter_2_rooms_&_scenery/adding_more_rooms_to_the_map.md'
        - 'The Great Outdoors': './chapter_2_rooms_&_scenery/the_great_outdoors.md'
        - 'Enterable Scenery': './chapter_2_rooms_&_scenery/enterable_scenery.md'
        - 'Doors': './chapter_2_rooms_&_scenery/doors.md'
        - 'Travel by Fiat': './chapter_2_rooms_&_scenery/travel_by_fiat.md'
        - 'Windows': './chapter_2_rooms_&_scenery/windows.md'
        - '“You can’t go that way.”': './chapter_2_rooms_&_scenery/you_cant_go_that_way.md'
        - 'Duplicate Exits & Twisty Connections': './chapter_2_rooms_&_scenery/duplicate_exits_&_twisty_connections.md'
        - 'Changing the Map During the Game': './chapter_2_rooms_&_scenery/changing_the_map_during_the_game.md'
        - 'Regions': './chapter_2_rooms_&_scenery/regions.md'
        - 'Backdrops': './chapter_2_rooms_&_scenery/backdrops.md'
        - 'Dark Rooms': './chapter_2_rooms_&_scenery/dark_rooms.md'
        - 'Seemingly Identical Rooms': './chapter_2_rooms_&_scenery/seemingly_identical_rooms.md'
        - 'Floorless Rooms': './chapter_2_rooms_&_scenery/floorless_rooms.md'
        - 'When Is a Room “visited”?': './chapter_2_rooms_&_scenery/when_is_a_room_visited.md'
        - 'More About Room Descriptions': './chapter_2_rooms_&_scenery/more_about_room_descriptions.md'
    - 'Chapter 3: Things':
        - 'Things': './chapter_3_things/things.md'
        - 'Creating Things': './chapter_3_things/creating_things.md'
        - 'Things vs. Kinds': './chapter_3_things/things_vs_kinds.md'
        - 'The Names of Things': './chapter_3_things/the_names_of_things.md'
        - 'Long Names': './chapter_3_things/long_names.md'
        - 'Initial Appearance': './chapter_3_things/initial_appearance.md'
        - 'Adding Vocabulary Words with “Understand”': './chapter_3_things/adding_vocabulary_words_with_understand.md'
        - 'Containers & Supporters': './chapter_3_things/containers_&_supporters.md'
        - 'Looking Under & Looking Behind': './chapter_3_things/looking_under_&_looking_behind.md'
        - 'Take All': './chapter_3_things/take_all.md'
        - 'Enterable Containers & Supporters': './chapter_3_things/enterable_containers_&_supporters.md'
        - 'Moving Things Around': './chapter_3_things/moving_things_around.md'
        - 'Inventory': './chapter_3_things/inventory.md'
        - 'Testing Where a Thing Is': './chapter_3_things/testing_where_a_thing_is.md'
        - 'Things Can Have Properties': './chapter_3_things/things_can_have_properties.md'
        - 'Plurals & Collective Objects': './chapter_3_things/plurals_&_collective_objects.md'
        - 'More about Collections & Kinds': './chapter_3_things/more_about_collections_&_kinds.md'
        - 'Objects That Have Parts': './chapter_3_things/objects_that_have_parts.md'
        - 'Reading Matter': './chapter_3_things/reading_matter.md'
        - 'Writing on Things': './chapter_3_things/writing_on_things.md'
        - 'Mechanical Marvels': './chapter_3_things/mechanical_marvels.md'
        - 'Smelling & Listening': './chapter_3_things/smelling_&_listening.md'
        - 'Transforming One Thing into Another': './chapter_3_things/transforming_one_thing_into_another.md'
        - 'New Ways to Use Things': './chapter_3_things/new_ways_to_use_things.md'
    - 'Chapter 4: Actions':
        - 'Actions': './chapter_4_actions/actions.md'
        - 'Built-In Actions': './chapter_4_actions/built-in_actions.md'
        - 'Using “Instead”': './chapter_4_actions/using_instead.md'
        - 'Action Processing': './chapter_4_actions/action_processing.md'
        - 'Rulebooks & “Stop the Action”': './chapter_4_actions/rulebooks_&_stop_the_action.md'
        - 'Three Types of Actions': './chapter_4_actions/three_types_of_actions.md'
        - 'Creating New Actions': './chapter_4_actions/creating_new_actions.md'
        - '[Any Thing]': './chapter_4_actions/[any_thing].md'
        - 'Same Action, New Results': './chapter_4_actions/same_action,_new_results.md'
        - 'Redirecting an Action': './chapter_4_actions/redirecting_an_action.md'
        - 'Actions with Topics': './chapter_4_actions/actions_with_topics.md'
        - 'Action Processing — Summary': './chapter_4_actions/action_processing__summary.md'
    - 'Chapter 5: Creating Characters':
        - 'Creating Characters': './chapter_5_creating_characters/creating_characters.md'
        - 'Overview': './chapter_5_creating_characters/overview.md'
        - 'The Player Character': './chapter_5_creating_characters/the_player_character.md'
        - 'Creating an NPC': './chapter_5_creating_characters/creating_an_npc.md'
        - 'Mr. & Mrs.': './chapter_5_creating_characters/mr_&_mrs.md'
        - 'Conversations, Part I: talk to': './chapter_5_creating_characters/conversations,_part_i_talk_to.md'
        - 'Conversations, Part II: ask/tell/give/show': './chapter_5_creating_characters/conversations,_part_ii_asktellgiveshow.md'
        - 'Conversations, Part III: Character Knowledge': './chapter_5_creating_characters/conversations,_part_iii_character_knowledge.md'
        - 'Conversations, Part IV: Menu-Based Conversation': './chapter_5_creating_characters/conversations,_part_iv_menu-based_conversation.md'
        - 'Giving Orders to Characters': './chapter_5_creating_characters/giving_orders_to_characters.md'
        - 'Giving Orders that Involve Going Elsewhere': './chapter_5_creating_characters/giving_orders_that_involve_going_elsewhere.md'
        - 'Moving Characters Around': './chapter_5_creating_characters/moving_characters_around.md'
        - 'Characters Who Follow the Player': './chapter_5_creating_characters/characters_who_follow_the_player.md'
        - 'Characters the Player Can Follow': './chapter_5_creating_characters/characters_the_player_can_follow.md'
        - 'Stage Business': './chapter_5_creating_characters/stage_business.md'
        - 'Character Actions': './chapter_5_creating_characters/character_actions.md'
        - 'Combat': './chapter_5_creating_characters/combat.md'
        - 'Moods': './chapter_5_creating_characters/moods.md'
        - 'Body Parts': './chapter_5_creating_characters/body_parts.md'
    - 'Chapter 6: Puzzles':
        - 'Puzzles': './chapter_6_puzzles/puzzles.md'
        - 'Mapping': './chapter_6_puzzles/mapping.md'
        - 'Blocked Passageways': './chapter_6_puzzles/blocked_passageways.md'
        - 'Darkness': './chapter_6_puzzles/darkness.md'
        - 'Hidden Items': './chapter_6_puzzles/hidden_items.md'
        - 'Items Out of Reach': './chapter_6_puzzles/items_out_of_reach.md'
        - 'Locked Containers': './chapter_6_puzzles/locked_containers.md'
        - 'Combination Locks': './chapter_6_puzzles/combination_locks.md'
        - 'Manipulation Difficulties': './chapter_6_puzzles/manipulation_difficulties.md'
        - 'Enigmas': './chapter_6_puzzles/enigmas.md'
        - 'Deceptive Appearances & Unusual Usages': './chapter_6_puzzles/deceptive_appearances_&_unusual_usages.md'
        - 'Assembly Required': './chapter_6_puzzles/assembly_required.md'
        - 'Mechanisms': './chapter_6_puzzles/mechanisms.md'
        - 'Vehicles': './chapter_6_puzzles/vehicles.md'
        - 'Consulting Information Sources': './chapter_6_puzzles/consulting_information_sources.md'
        - 'The Uncooperative Character': './chapter_6_puzzles/the_uncooperative_character.md'
        - 'Timed Puzzles': './chapter_6_puzzles/timed_puzzles.md'
        - 'Inadequate Implementation': './chapter_6_puzzles/inadequate_implementation.md'
    - 'Chapter 7: Winning & Losing':
        - 'Winning & Losing': './chapter_7_winning_&_losing/winning_losing.md'
        - 'A Word About Fairness': './chapter_7_winning_&_losing/a_word_about_fairness.md'
        - 'Keeping Score': './chapter_7_winning_&_losing/keeping_score.md'
        - 'Achievements': './chapter_7_winning_&_losing/achievements.md'
    - 'Chapter 8: Time & Scenes':
        - 'Time & Scenes': './chapter_8_time_&_scenes/time_scenes.md'
        - 'Passing Time': './chapter_8_time_&_scenes/passing_time.md'
        - 'Future Events': './chapter_8_time_&_scenes/future_events.md'
        - 'Scenes': './chapter_8_time_&_scenes/scenes.md'
        - 'Every Turn Rules': './chapter_8_time_&_scenes/every_turn_rules.md'
    - 'Chapter 9: Phrasing & Punctuation':
        - 'Phrasing & Punctuation': './chapter_9_phrasing_&_punctuation/phrasing_punctuation.md'
        - 'Types of Source Text': './chapter_9_phrasing_&_punctuation/types_of_source_text.md'
        - 'Text Insertions': './chapter_9_phrasing_&_punctuation/text_insertions.md'
        - 'Breaking Up Paragraphs': './chapter_9_phrasing_&_punctuation/breaking_up_paragraphs.md'
        - 'Large Text Blocks': './chapter_9_phrasing_&_punctuation/large_text_blocks.md'
        - 'White Space': './chapter_9_phrasing_&_punctuation/white_space.md'
        - 'Objects vs. Rules': './chapter_9_phrasing_&_punctuation/objects_vs_rules.md'
        - 'The Names of Things': './chapter_9_phrasing_&_punctuation/the_names_of_things.md'
        - 'Punctuation': './chapter_9_phrasing_&_punctuation/punctuation.md'
        - 'Assertions': './chapter_9_phrasing_&_punctuation/assertions.md'
        - 'Values': './chapter_9_phrasing_&_punctuation/values.md'
        - 'Arithmetic': './chapter_9_phrasing_&_punctuation/arithmetic.md'
        - 'Doing Calculations': './chapter_9_phrasing_&_punctuation/doing_calculations.md'
        - 'Testing Conditions': './chapter_9_phrasing_&_punctuation/testing_conditions.md'
        - 'Creating New Phrases': './chapter_9_phrasing_&_punctuation/creating_new_phrases.md'
        - 'Indenting': './chapter_9_phrasing_&_punctuation/indenting.md'
        - 'Headings': './chapter_9_phrasing_&_punctuation/headings.md'
        - 'Loops': './chapter_9_phrasing_&_punctuation/loops.md'
    - 'Chapter 10: Advanced Topics':
        - 'Advanced Topics': './chapter_10_advanced_topics/advanced_topics.md'
        - 'Story Tense and Viewpoint': './chapter_10_advanced_topics/story_tense_and_viewpoint.md'
        - 'Code Optimization': './chapter_10_advanced_topics/code_optimization.md'
        - 'Tables': './chapter_10_advanced_topics/tables.md'
        - 'The Skein': './chapter_10_advanced_topics/the_skein.md'
        - 'Using the Index': './chapter_10_advanced_topics/using_the_index.md'
        - 'Replacing Rules in the Standard Library': './chapter_10_advanced_topics/replacing_rules_in_the_standard_library.md'
        - 'Helping the Parser': './chapter_10_advanced_topics/helping_the_parser.md'
        - 'Clearing the Screen': './chapter_10_advanced_topics/clearing_the_screen.md'
        - 'I6 Constants': './chapter_10_advanced_topics/i6_constants.md'
        - 'Relations': './chapter_10_advanced_topics/relations.md'
        - 'Adding Hints': './chapter_10_advanced_topics/adding_hints.md'
        - 'Special Features in Glulx': './chapter_10_advanced_topics/special_features_in_glulx.md'
        - 'What Does Inform 6 Have to Do with Inform 7?': './chapter_10_advanced_topics/what_does_inform_6_have_to_do_with_inform_7.md'
        - 'So, Is Inform 7 the Ultimate IF Programming Language?': './chapter_10_advanced_topics/so,_is_inform_7_the_ultimate_if_programming_langua.md'
    - 'Appendix A: Glossary': 'GLOSSARY.md'
    - 'Appendix B: Updating Older Extensions': 'appendix_b_updating_older_extensions.md'
    - 'Appendix C: Short Sample Games':
        - 'Short Sample Games': './appendix_c_short_sample_games/short_sample_games.md'
        - 'Flea Market': './appendix_c_short_sample_games/flea_market.md'
        - 'Mr Potato Head': './appendix_c_short_sample_games/mr_potato_head.md'
        - 'A Dangerous Jewel Box': './appendix_c_short_sample_games/a_dangerous_jewel_box.md'
        - 'The Omega Machine': './appendix_c_short_sample_games/the_omega_machine.md'
        - 'The Lurking Critter': './appendix_c_short_sample_games/the_lurking_critter.md'
        - 'Restraints': './appendix_c_short_sample_games/restraints.md'
        - 'Broken Eggs': './appendix_c_short_sample_games/broken_eggs.md'
        - 'Indoors & Outdoors': './appendix_c_short_sample_games/indoors_&_outdoors.md'
    - 'Appendix D: License': 'appendix_d_license.md'
