site_name: I7 Handbook
site_url: https://github.com/omartek/I7handbook_byJimAikin
docs_dir: gitbook/
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - inform7
nav:
        - 'Chapter 1 - Getting started':
                - 'Getting_started': '/chapter_1_getting_started/getting_started.md'
                - 'Getting_started': '/chapter_1_getting_started/downloading_&_installing.md'
                - 'The Inform 7 Program': '/chapter_1_getting_started/the_inform_7_program.md'
                - 'Using the Built-In Documentation': '/chapter_1_getting_started/using_the_built-in_documentation.md'
                - 'What Happens in a Game': '/chapter_1_getting_started/what_happens_in_a_game.md'
                - 'Downloading & Playing Games': '/chapter_1_getting_started/downloading_&_playing_games.md'
                - 'Writing Your First Game': '/chapter_1_getting_started/writing_your_first_game.md'
                - 'All About Bugs': '/chapter_1_getting_started/all_about_bugs.md'
                - 'Testing Your Game': '/chapter_1_getting_started/testing_your_game.md'
                - 'Using the Debugging Commands': '/chapter_1_getting_started/using_the_debugging_commands.md'
                - 'Puzzles': '/chapter_1_getting_started/puzzles.md'
                - 'Extensions for Inform': '/chapter_1_getting_started/extensions_for_inform.md'
                - 'Where to Learn More': '/chapter_1_getting_started/where_to_learn_more.md'
        - 'Chapter 2: Rooms & Scenery':
                - 'Rooms & Scenery': 'chapter_2_rooms_&_scenery/rooms_&_scenery.md'
                - 'Creating Your First Room': 'chapter_2_rooms_&_scenery/creating_your_first_room.md'
                - 'Scenery': 'chapter_2_rooms_&_scenery/scenery.md'
                - 'Distant Scenery': 'chapter_2_rooms_&_scenery/distant_scenery.md'
                - 'Adding More Rooms to the Map': 'chapter_2_rooms_&_scenery/adding_more_rooms_to_the_map.md'
                - 'The Great Outdoors': 'chapter_2_rooms_&_scenery/the_great_outdoors.md'
                - 'Enterable Scenery': 'chapter_2_rooms_&_scenery/enterable_scenery.md'
                - 'Doors': 'chapter_2_rooms_&_scenery/doors.md'
                - 'Travel by Fiat': 'chapter_2_rooms_&_scenery/travel_by_fiat.md'
                - 'Windows': 'chapter_2_rooms_&_scenery/windows.md'
                - '“You can’t go that way.”': 'chapter_2_rooms_&_scenery/you_cant_go_that_way.md'
                - 'Duplicate Exits & Twisty Connections': 'chapter_2_rooms_&_scenery/duplicate_exits_&_twisty_connections.md'
                - 'Changing the Map During the Game': 'chapter_2_rooms_&_scenery/changing_the_map_during_the_game.md'
                - 'Regions': 'chapter_2_rooms_&_scenery/regions.md'
                - 'Backdrops': 'chapter_2_rooms_&_scenery/backdrops.md'
                - 'Dark Rooms': 'chapter_2_rooms_&_scenery/dark_rooms.md'
                - 'Seemingly Identical Rooms': 'chapter_2_rooms_&_scenery/seemingly_identical_rooms.md'
                - 'Floorless Rooms': 'chapter_2_rooms_&_scenery/floorless_rooms.md'
                - 'When Is a Room “visited”?': 'chapter_2_rooms_&_scenery/when_is_a_room_visited.md'
                - 'More About Room Descriptions': 'chapter_2_rooms_&_scenery/more_about_room_descriptions.md'
